# Generated by Django 3.2 on 2023-08-19 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_age', models.CharField(max_length=10)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('hitcount', models.IntegerField(default=0)),
                ('image_del', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
